### ISSUE TITLE
Need thumbnail for xmind file

### ISSUE THREAD

**Issue by l0o0** [mriza/XMind-Linux-Installer#12]
I install Xmind as the instruction. After updated mime database, I can open xmind file by double click.  
But I think you should provide a thumbnail for xmind file.  

Below is what xmind file looks in nautlius.

![image](https://user-images.githubusercontent.com/2743744/42368224-114295e0-8139-11e8-95a1-e4e8be64920f.png)

**Comment by l0o0** [comment]
According to this [thread](https://elementaryos.stackexchange.com/questions/3995/how-can-i-change-the-icon-for-a-specific-file-type). 
`xmind.xml ` was created under `/usr/share/mime/packages` with the content below:
```xml
<?xml version="1.0" encoding="utf-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/x-xmind">
    <comment>Xmind files</comment>
    <icon name="application-x-xmind"/>
    <glob pattern="*.XMIND"/>
    <glob pattern="*.xmind"/>
  </mime-type>
</mime-info>
```
Then I downloaded an [icon](https://www.easyicon.net/1185142-Mind_Map_Paper_icon.html).  Move the icon to `/usr/share/icons/gnome/scalable/mimetypes`   
```bash
sudo mv downloaded.svg /usr/share/icons/gnome/scalable/mimetypes/application-x-xmind.svg
sudo update-mime-database /usr/share/mime   
sudo gtk-update-icon-cache /usr/share/icons/gnome
```

Now Xmind file looks 
![image](https://user-images.githubusercontent.com/2743744/42433469-1368c664-8382-11e8-96e6-e68e1f21a331.png)

**Comment by mriza** [comment]
icon and mimitype has been supported, please check again
