### ISSUE TITLE
Can't open XMind files on Nautilus

### ISSUE THREAD

**Issue by kenjis** [mriza/XMind-Linux-Installer#13]
Thank you for the installer. It installed XMind fine.

But when I double click a XMind file on Nautilus, it does not open.
I can open XMind files from open menu in XMind.

I use Ubuntu 18.04 (ja).

**Comment by kenjis** [comment]
I added `MimeType=application/mindmap` in the end of `/usr/share/applications/xmind8.desktop`.

**Comment by mriza** [comment]
I've just update the .desktop file. Thanks for the suggestion.
