### ISSUE TITLE
For uninstalling xmind8..

### ISSUE THREAD

**Issue by ghost** [mriza/XMind-Linux-Installer#19]
"/home/USER/configuration/"
This folder is also created by xmind8 which didn't get deleted when executing " 	uninstall.sh "
![Screenshot from 2019-12-22 00-08-16](https://user-images.githubusercontent.com/52375886/71310489-ab1c5b00-244f-11ea-90e3-65e82335feb7.png)

**Comment by Solar-Lancelo** [comment]
This is one of the error logs.
[1576940772806.log](https://github.com/mriza/XMind-Linux-Installer/files/3991568/1576940772806.log)

**Comment by mriza** [comment]
If you have an ECLIPSE-based application installed on the same computer, deleting this folder can create a disaster. If you sure don't have any eclipsed or ECLIPSE-based applications, you can remove it manually.
