### ISSUE TITLE
xmind 8 update 9 doens't work 

### ISSUE THREAD

**Issue by olli0815** [mriza/XMind-Linux-Installer#22]
JVM terminated. Exit code=1
/usr/bin/java
-Dfile.encoding=UTF-8
--add-modules=java.se.ee
-Dosgi.requiredJavaVersion=1.8
-Xms256m
-Xmx1024m
-jar /opt/xmind/plugins/org.eclipse.equinox.launcher_1.3.200.v20160318-1642.jar
-os linux
-ws gtk
-arch x86_64
-showsplash
-launcher /opt/xmind/XMind_amd64/XMind
-name XMind
--launcher.library /opt/xmind/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.400.v20160518-1444/eclipse_1617.so
-startup /opt/xmind/plugins/org.eclipse.equinox.launcher_1.3.200.v20160318-1642.jar
--launcher.overrideVmargs
-exitdata 30022
-configuration @user.home/.configuration
-data @user.home/workspace
-eclipse.keyring @user.home/.xmind/secure_storage_linux
-vm /usr/bin/java
-vmargs
-Dfile.encoding=UTF-8
--add-modules=java.se.ee
-Dosgi.requiredJavaVersion=1.8
-Xms256m
-Xmx1024m
-jar /opt/xmind/plugins/org.eclipse.equinox.launcher_1.3.200.v20160318-1642.jar

**Comment by mriza** [comment]
should run using the latest updated script #17
